## This file provides default values to modules using the secrets-gradle-plugin. It is necessary
# because the secrets properties file is not under source control so CI builds will fail without
# default values.
app.name=Cinebox
app.id=com.stanleymesa.cinebox
app.version.code=1
app.version.name=1.0.0
baseUrl.stag="https://backend-v2.portalsiswa.id/"
baseUrl.testing="https://backend-v2.promisedland.id/"
baseUrl.prod="https://backend.portalsekolah.co.id/"
sdk.compile=35
sdk.target=35
sdk.min=24